spring:
  batch:
    initialize-schema: always
  h2:
    console:
      enabled: true


datasource:
  batch:
    username: ramideltoro
    password: password
    jdbcUrl: jdbc:mysql://localhost:3306/spring_batch
    driverClassName: com.mysql.jdbc.Driver
    platform: mysql
    continueOnError: false


