spring:
  batch:
    initialize-schema: always
  h2:
    console:
      enabled: true

datasource:
  batch:
     username: sa
     password:
     jdbcUrl: jdbc:h2:mem:testdb
     driverClassName: org.h2.Driver


#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect